// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/vipshark78/microservices-course-homeworks/inventory/internal/model"

	repositorymodel "github.com/vipshark78/microservices-course-homeworks/inventory/internal/repository/model"

	uuid "github.com/google/uuid"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

type InventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRepository) EXPECT() *InventoryRepository_Expecter {
	return &InventoryRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, _a1
func (_m *InventoryRepository) GetPart(ctx context.Context, _a1 uuid.UUID) (model.Part, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *InventoryRepository_Expecter) GetPart(ctx interface{}, _a1 interface{}) *InventoryRepository_GetPart_Call {
	return &InventoryRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, _a1)}
}

func (_c *InventoryRepository_GetPart_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *InventoryRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *InventoryRepository_GetPart_Call) Return(_a0 model.Part, _a1 error) *InventoryRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_GetPart_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Part, error)) *InventoryRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: ctx
func (_m *InventoryRepository) Init(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryRepository_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type InventoryRepository_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *InventoryRepository_Expecter) Init(ctx interface{}) *InventoryRepository_Init_Call {
	return &InventoryRepository_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *InventoryRepository_Init_Call) Run(run func(ctx context.Context)) *InventoryRepository_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *InventoryRepository_Init_Call) Return(_a0 error) *InventoryRepository_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryRepository_Init_Call) RunAndReturn(run func(context.Context) error) *InventoryRepository_Init_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPart provides a mock function with given fields: ctx, part
func (_m *InventoryRepository) InsertPart(ctx context.Context, part repositorymodel.Part) error {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for InsertPart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repositorymodel.Part) error); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryRepository_InsertPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPart'
type InventoryRepository_InsertPart_Call struct {
	*mock.Call
}

// InsertPart is a helper method to define mock.On call
//   - ctx context.Context
//   - part repositorymodel.Part
func (_e *InventoryRepository_Expecter) InsertPart(ctx interface{}, part interface{}) *InventoryRepository_InsertPart_Call {
	return &InventoryRepository_InsertPart_Call{Call: _e.mock.On("InsertPart", ctx, part)}
}

func (_c *InventoryRepository_InsertPart_Call) Run(run func(ctx context.Context, part repositorymodel.Part)) *InventoryRepository_InsertPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repositorymodel.Part))
	})
	return _c
}

func (_c *InventoryRepository_InsertPart_Call) Return(_a0 error) *InventoryRepository_InsertPart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryRepository_InsertPart_Call) RunAndReturn(run func(context.Context, repositorymodel.Part) error) *InventoryRepository_InsertPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *InventoryRepository) ListParts(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *InventoryRepository_Expecter) ListParts(ctx interface{}, filter interface{}) *InventoryRepository_ListParts_Call {
	return &InventoryRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *InventoryRepository_ListParts_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *InventoryRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *InventoryRepository_ListParts_Call) Return(_a0 []model.Part, _a1 error) *InventoryRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_ListParts_Call) RunAndReturn(run func(context.Context, model.PartsFilter) ([]model.Part, error)) *InventoryRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
