// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderAssembledConsumerService is an autogenerated mock type for the OrderAssembledConsumerService type
type OrderAssembledConsumerService struct {
	mock.Mock
}

type OrderAssembledConsumerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderAssembledConsumerService) EXPECT() *OrderAssembledConsumerService_Expecter {
	return &OrderAssembledConsumerService_Expecter{mock: &_m.Mock}
}

// RunConsumer provides a mock function with given fields: ctx
func (_m *OrderAssembledConsumerService) RunConsumer(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunConsumer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderAssembledConsumerService_RunConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunConsumer'
type OrderAssembledConsumerService_RunConsumer_Call struct {
	*mock.Call
}

// RunConsumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderAssembledConsumerService_Expecter) RunConsumer(ctx interface{}) *OrderAssembledConsumerService_RunConsumer_Call {
	return &OrderAssembledConsumerService_RunConsumer_Call{Call: _e.mock.On("RunConsumer", ctx)}
}

func (_c *OrderAssembledConsumerService_RunConsumer_Call) Run(run func(ctx context.Context)) *OrderAssembledConsumerService_RunConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderAssembledConsumerService_RunConsumer_Call) Return(_a0 error) *OrderAssembledConsumerService_RunConsumer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderAssembledConsumerService_RunConsumer_Call) RunAndReturn(run func(context.Context) error) *OrderAssembledConsumerService_RunConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderAssembledConsumerService creates a new instance of OrderAssembledConsumerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderAssembledConsumerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderAssembledConsumerService {
	mock := &OrderAssembledConsumerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
