// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/vipshark78/microservices-course-homeworks/notification/internal/model"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

type NotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationService) EXPECT() *NotificationService_Expecter {
	return &NotificationService_Expecter{mock: &_m.Mock}
}

// SendOrderAssembledNotification provides a mock function with given fields: ctx, notification
func (_m *NotificationService) SendOrderAssembledNotification(ctx context.Context, notification model.OrderAssembledEvent) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderAssembledNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderAssembledEvent) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_SendOrderAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderAssembledNotification'
type NotificationService_SendOrderAssembledNotification_Call struct {
	*mock.Call
}

// SendOrderAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notification model.OrderAssembledEvent
func (_e *NotificationService_Expecter) SendOrderAssembledNotification(ctx interface{}, notification interface{}) *NotificationService_SendOrderAssembledNotification_Call {
	return &NotificationService_SendOrderAssembledNotification_Call{Call: _e.mock.On("SendOrderAssembledNotification", ctx, notification)}
}

func (_c *NotificationService_SendOrderAssembledNotification_Call) Run(run func(ctx context.Context, notification model.OrderAssembledEvent)) *NotificationService_SendOrderAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderAssembledEvent))
	})
	return _c
}

func (_c *NotificationService_SendOrderAssembledNotification_Call) Return(_a0 error) *NotificationService_SendOrderAssembledNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_SendOrderAssembledNotification_Call) RunAndReturn(run func(context.Context, model.OrderAssembledEvent) error) *NotificationService_SendOrderAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendOrderPaidNotification provides a mock function with given fields: ctx, notification
func (_m *NotificationService) SendOrderPaidNotification(ctx context.Context, notification model.OrderPaidEvent) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPaidNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_SendOrderPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPaidNotification'
type NotificationService_SendOrderPaidNotification_Call struct {
	*mock.Call
}

// SendOrderPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notification model.OrderPaidEvent
func (_e *NotificationService_Expecter) SendOrderPaidNotification(ctx interface{}, notification interface{}) *NotificationService_SendOrderPaidNotification_Call {
	return &NotificationService_SendOrderPaidNotification_Call{Call: _e.mock.On("SendOrderPaidNotification", ctx, notification)}
}

func (_c *NotificationService_SendOrderPaidNotification_Call) Run(run func(ctx context.Context, notification model.OrderPaidEvent)) *NotificationService_SendOrderPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidEvent))
	})
	return _c
}

func (_c *NotificationService_SendOrderPaidNotification_Call) Return(_a0 error) *NotificationService_SendOrderPaidNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_SendOrderPaidNotification_Call) RunAndReturn(run func(context.Context, model.OrderPaidEvent) error) *NotificationService_SendOrderPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
