// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// OrderAssembledConsumerConfig is an autogenerated mock type for the OrderAssembledConsumerConfig type
type OrderAssembledConsumerConfig struct {
	mock.Mock
}

type OrderAssembledConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderAssembledConsumerConfig) EXPECT() *OrderAssembledConsumerConfig_Expecter {
	return &OrderAssembledConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *OrderAssembledConsumerConfig) Config() *sarama.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if rf, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}

	return r0
}

// OrderAssembledConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type OrderAssembledConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *OrderAssembledConsumerConfig_Expecter) Config() *OrderAssembledConsumerConfig_Config_Call {
	return &OrderAssembledConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *OrderAssembledConsumerConfig_Config_Call) Run(run func()) *OrderAssembledConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderAssembledConsumerConfig_Config_Call) Return(_a0 *sarama.Config) *OrderAssembledConsumerConfig_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderAssembledConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *OrderAssembledConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function with no fields
func (_m *OrderAssembledConsumerConfig) GroupID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderAssembledConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type OrderAssembledConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *OrderAssembledConsumerConfig_Expecter) GroupID() *OrderAssembledConsumerConfig_GroupID_Call {
	return &OrderAssembledConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *OrderAssembledConsumerConfig_GroupID_Call) Run(run func()) *OrderAssembledConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderAssembledConsumerConfig_GroupID_Call) Return(_a0 string) *OrderAssembledConsumerConfig_GroupID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderAssembledConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *OrderAssembledConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *OrderAssembledConsumerConfig) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderAssembledConsumerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type OrderAssembledConsumerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *OrderAssembledConsumerConfig_Expecter) Topic() *OrderAssembledConsumerConfig_Topic_Call {
	return &OrderAssembledConsumerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *OrderAssembledConsumerConfig_Topic_Call) Run(run func()) *OrderAssembledConsumerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *OrderAssembledConsumerConfig_Topic_Call) Return(_a0 string) *OrderAssembledConsumerConfig_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderAssembledConsumerConfig_Topic_Call) RunAndReturn(run func() string) *OrderAssembledConsumerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderAssembledConsumerConfig creates a new instance of OrderAssembledConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderAssembledConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderAssembledConsumerConfig {
	mock := &OrderAssembledConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
