// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TelegramBotConfig is an autogenerated mock type for the TelegramBotConfig type
type TelegramBotConfig struct {
	mock.Mock
}

type TelegramBotConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramBotConfig) EXPECT() *TelegramBotConfig_Expecter {
	return &TelegramBotConfig_Expecter{mock: &_m.Mock}
}

// BotToken provides a mock function with no fields
func (_m *TelegramBotConfig) BotToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BotToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TelegramBotConfig_BotToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BotToken'
type TelegramBotConfig_BotToken_Call struct {
	*mock.Call
}

// BotToken is a helper method to define mock.On call
func (_e *TelegramBotConfig_Expecter) BotToken() *TelegramBotConfig_BotToken_Call {
	return &TelegramBotConfig_BotToken_Call{Call: _e.mock.On("BotToken")}
}

func (_c *TelegramBotConfig_BotToken_Call) Run(run func()) *TelegramBotConfig_BotToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramBotConfig_BotToken_Call) Return(_a0 string) *TelegramBotConfig_BotToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramBotConfig_BotToken_Call) RunAndReturn(run func() string) *TelegramBotConfig_BotToken_Call {
	_c.Call.Return(run)
	return _c
}

// ChatID provides a mock function with no fields
func (_m *TelegramBotConfig) ChatID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// TelegramBotConfig_ChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatID'
type TelegramBotConfig_ChatID_Call struct {
	*mock.Call
}

// ChatID is a helper method to define mock.On call
func (_e *TelegramBotConfig_Expecter) ChatID() *TelegramBotConfig_ChatID_Call {
	return &TelegramBotConfig_ChatID_Call{Call: _e.mock.On("ChatID")}
}

func (_c *TelegramBotConfig_ChatID_Call) Run(run func()) *TelegramBotConfig_ChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TelegramBotConfig_ChatID_Call) Return(_a0 int64) *TelegramBotConfig_ChatID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramBotConfig_ChatID_Call) RunAndReturn(run func() int64) *TelegramBotConfig_ChatID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramBotConfig creates a new instance of TelegramBotConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramBotConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramBotConfig {
	mock := &TelegramBotConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
