// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KafkaConfig is an autogenerated mock type for the KafkaConfig type
type KafkaConfig struct {
	mock.Mock
}

type KafkaConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *KafkaConfig) EXPECT() *KafkaConfig_Expecter {
	return &KafkaConfig_Expecter{mock: &_m.Mock}
}

// Brokers provides a mock function with no fields
func (_m *KafkaConfig) Brokers() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Brokers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// KafkaConfig_Brokers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Brokers'
type KafkaConfig_Brokers_Call struct {
	*mock.Call
}

// Brokers is a helper method to define mock.On call
func (_e *KafkaConfig_Expecter) Brokers() *KafkaConfig_Brokers_Call {
	return &KafkaConfig_Brokers_Call{Call: _e.mock.On("Brokers")}
}

func (_c *KafkaConfig_Brokers_Call) Run(run func()) *KafkaConfig_Brokers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KafkaConfig_Brokers_Call) Return(_a0 []string) *KafkaConfig_Brokers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KafkaConfig_Brokers_Call) RunAndReturn(run func() []string) *KafkaConfig_Brokers_Call {
	_c.Call.Return(run)
	return _c
}

// NewKafkaConfig creates a new instance of KafkaConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaConfig {
	mock := &KafkaConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
