// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/vipshark78/microservices-course-homeworks/iam/internal/model"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *AuthService) Login(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 string, _a1 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function with given fields: ctx, sessionUuid
func (_m *AuthService) Whoami(ctx context.Context, sessionUuid string) (model.WhoamiResponse, error) {
	ret := _m.Called(ctx, sessionUuid)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 model.WhoamiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.WhoamiResponse, error)); ok {
		return rf(ctx, sessionUuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.WhoamiResponse); ok {
		r0 = rf(ctx, sessionUuid)
	} else {
		r0 = ret.Get(0).(model.WhoamiResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionUuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type AuthService_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUuid string
func (_e *AuthService_Expecter) Whoami(ctx interface{}, sessionUuid interface{}) *AuthService_Whoami_Call {
	return &AuthService_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUuid)}
}

func (_c *AuthService_Whoami_Call) Run(run func(ctx context.Context, sessionUuid string)) *AuthService_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Whoami_Call) Return(_a0 model.WhoamiResponse, _a1 error) *AuthService_Whoami_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Whoami_Call) RunAndReturn(run func(context.Context, string) (model.WhoamiResponse, error)) *AuthService_Whoami_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
