// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// SessionConfig is an autogenerated mock type for the SessionConfig type
type SessionConfig struct {
	mock.Mock
}

type SessionConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionConfig) EXPECT() *SessionConfig_Expecter {
	return &SessionConfig_Expecter{mock: &_m.Mock}
}

// SessionTTL provides a mock function with no fields
func (_m *SessionConfig) SessionTTL() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SessionTTL")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// SessionConfig_SessionTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionTTL'
type SessionConfig_SessionTTL_Call struct {
	*mock.Call
}

// SessionTTL is a helper method to define mock.On call
func (_e *SessionConfig_Expecter) SessionTTL() *SessionConfig_SessionTTL_Call {
	return &SessionConfig_SessionTTL_Call{Call: _e.mock.On("SessionTTL")}
}

func (_c *SessionConfig_SessionTTL_Call) Run(run func()) *SessionConfig_SessionTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SessionConfig_SessionTTL_Call) Return(_a0 time.Duration) *SessionConfig_SessionTTL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionConfig_SessionTTL_Call) RunAndReturn(run func() time.Duration) *SessionConfig_SessionTTL_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionConfig creates a new instance of SessionConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionConfig {
	mock := &SessionConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
