// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAMGRPCConfig is an autogenerated mock type for the IAMGRPCConfig type
type IAMGRPCConfig struct {
	mock.Mock
}

type IAMGRPCConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *IAMGRPCConfig) EXPECT() *IAMGRPCConfig_Expecter {
	return &IAMGRPCConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *IAMGRPCConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IAMGRPCConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type IAMGRPCConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *IAMGRPCConfig_Expecter) Address() *IAMGRPCConfig_Address_Call {
	return &IAMGRPCConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *IAMGRPCConfig_Address_Call) Run(run func()) *IAMGRPCConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAMGRPCConfig_Address_Call) Return(_a0 string) *IAMGRPCConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAMGRPCConfig_Address_Call) RunAndReturn(run func() string) *IAMGRPCConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAMGRPCConfig creates a new instance of IAMGRPCConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAMGRPCConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAMGRPCConfig {
	mock := &IAMGRPCConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
