// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/vipshark78/microservices-course-homeworks/assembly/internal/model"
)

// ProducerService is an autogenerated mock type for the ProducerService type
type ProducerService struct {
	mock.Mock
}

type ProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProducerService) EXPECT() *ProducerService_Expecter {
	return &ProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderAssembled provides a mock function with given fields: ctx, event
func (_m *ProducerService) ProduceOrderAssembled(ctx context.Context, event model.OrderAssembledEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderAssembled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderAssembledEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProducerService_ProduceOrderAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderAssembled'
type ProducerService_ProduceOrderAssembled_Call struct {
	*mock.Call
}

// ProduceOrderAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderAssembledEvent
func (_e *ProducerService_Expecter) ProduceOrderAssembled(ctx interface{}, event interface{}) *ProducerService_ProduceOrderAssembled_Call {
	return &ProducerService_ProduceOrderAssembled_Call{Call: _e.mock.On("ProduceOrderAssembled", ctx, event)}
}

func (_c *ProducerService_ProduceOrderAssembled_Call) Run(run func(ctx context.Context, event model.OrderAssembledEvent)) *ProducerService_ProduceOrderAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderAssembledEvent))
	})
	return _c
}

func (_c *ProducerService_ProduceOrderAssembled_Call) Return(_a0 error) *ProducerService_ProduceOrderAssembled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProducerService_ProduceOrderAssembled_Call) RunAndReturn(run func(context.Context, model.OrderAssembledEvent) error) *ProducerService_ProduceOrderAssembled_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducerService creates a new instance of ProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerService {
	mock := &ProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
