// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: events/v1/order.proto

package events_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderPaid сообщение об оплате заказа
type OrderPaid struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventUuid       string                 `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	OrderUuid       string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid        string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransactionUuid string                 `protobuf:"bytes,5,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderPaid) Reset() {
	*x = OrderPaid{}
	mi := &file_events_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaid) ProtoMessage() {}

func (x *OrderPaid) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaid.ProtoReflect.Descriptor instead.
func (*OrderPaid) Descriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaid) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderPaid) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderPaid) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *OrderPaid) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderPaid) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

// OrderPaid сообщение об оплате заказа
type OrderAssembled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventUuid     string                 `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	OrderUuid     string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid      string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	BuildTimeSec  int64                  `protobuf:"varint,4,opt,name=build_time_sec,json=buildTimeSec,proto3" json:"build_time_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAssembled) Reset() {
	*x = OrderAssembled{}
	mi := &file_events_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAssembled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAssembled) ProtoMessage() {}

func (x *OrderAssembled) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAssembled.ProtoReflect.Descriptor instead.
func (*OrderAssembled) Descriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderAssembled) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderAssembled) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderAssembled) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *OrderAssembled) GetBuildTimeSec() int64 {
	if x != nil {
		return x.BuildTimeSec
	}
	return 0
}

var File_events_v1_order_proto protoreflect.FileDescriptor

const file_events_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/order.proto\x12\tevents.v1\"\xb8\x01\n" +
	"\tOrderPaid\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tR\x0ftransactionUuid\"\x91\x01\n" +
	"\x0eOrderAssembled\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12$\n" +
	"\x0ebuild_time_sec\x18\x04 \x01(\x03R\fbuildTimeSecB[ZYgithub.com/vipshark78/microservices-course-homeworks/shared/pkg/proto/events/v1;events_v1b\x06proto3"

var (
	file_events_v1_order_proto_rawDescOnce sync.Once
	file_events_v1_order_proto_rawDescData []byte
)

func file_events_v1_order_proto_rawDescGZIP() []byte {
	file_events_v1_order_proto_rawDescOnce.Do(func() {
		file_events_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)))
	})
	return file_events_v1_order_proto_rawDescData
}

var file_events_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_v1_order_proto_goTypes = []any{
	(*OrderPaid)(nil),      // 0: events.v1.OrderPaid
	(*OrderAssembled)(nil), // 1: events.v1.OrderAssembled
}
var file_events_v1_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_order_proto_init() }
func file_events_v1_order_proto_init() {
	if File_events_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_order_proto_goTypes,
		DependencyIndexes: file_events_v1_order_proto_depIdxs,
		MessageInfos:      file_events_v1_order_proto_msgTypes,
	}.Build()
	File_events_v1_order_proto = out.File
	file_events_v1_order_proto_goTypes = nil
	file_events_v1_order_proto_depIdxs = nil
}
