// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MongoConfig is an autogenerated mock type for the MongoConfig type
type MongoConfig struct {
	mock.Mock
}

type MongoConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MongoConfig) EXPECT() *MongoConfig_Expecter {
	return &MongoConfig_Expecter{mock: &_m.Mock}
}

// DatabaseName provides a mock function with no fields
func (_m *MongoConfig) DatabaseName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MongoConfig_DatabaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseName'
type MongoConfig_DatabaseName_Call struct {
	*mock.Call
}

// DatabaseName is a helper method to define mock.On call
func (_e *MongoConfig_Expecter) DatabaseName() *MongoConfig_DatabaseName_Call {
	return &MongoConfig_DatabaseName_Call{Call: _e.mock.On("DatabaseName")}
}

func (_c *MongoConfig_DatabaseName_Call) Run(run func()) *MongoConfig_DatabaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoConfig_DatabaseName_Call) Return(_a0 string) *MongoConfig_DatabaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoConfig_DatabaseName_Call) RunAndReturn(run func() string) *MongoConfig_DatabaseName_Call {
	_c.Call.Return(run)
	return _c
}

// URI provides a mock function with no fields
func (_m *MongoConfig) URI() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for URI")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MongoConfig_URI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URI'
type MongoConfig_URI_Call struct {
	*mock.Call
}

// URI is a helper method to define mock.On call
func (_e *MongoConfig_Expecter) URI() *MongoConfig_URI_Call {
	return &MongoConfig_URI_Call{Call: _e.mock.On("URI")}
}

func (_c *MongoConfig_URI_Call) Run(run func()) *MongoConfig_URI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MongoConfig_URI_Call) Return(_a0 string) *MongoConfig_URI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoConfig_URI_Call) RunAndReturn(run func() string) *MongoConfig_URI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMongoConfig creates a new instance of MongoConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongoConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongoConfig {
	mock := &MongoConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
