// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/vipshark78/microservices-course-homeworks/iam/internal/model"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// AddToUserSet provides a mock function with given fields: ctx, userUUID, sessionUUID
func (_m *SessionRepository) AddToUserSet(ctx context.Context, userUUID string, sessionUUID string) error {
	ret := _m.Called(ctx, userUUID, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for AddToUserSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userUUID, sessionUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_AddToUserSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToUserSet'
type SessionRepository_AddToUserSet_Call struct {
	*mock.Call
}

// AddToUserSet is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - sessionUUID string
func (_e *SessionRepository_Expecter) AddToUserSet(ctx interface{}, userUUID interface{}, sessionUUID interface{}) *SessionRepository_AddToUserSet_Call {
	return &SessionRepository_AddToUserSet_Call{Call: _e.mock.On("AddToUserSet", ctx, userUUID, sessionUUID)}
}

func (_c *SessionRepository_AddToUserSet_Call) Run(run func(ctx context.Context, userUUID string, sessionUUID string)) *SessionRepository_AddToUserSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SessionRepository_AddToUserSet_Call) Return(_a0 error) *SessionRepository_AddToUserSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_AddToUserSet_Call) RunAndReturn(run func(context.Context, string, string) error) *SessionRepository_AddToUserSet_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userUUID
func (_m *SessionRepository) Create(ctx context.Context, userUUID string) (string, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
func (_e *SessionRepository_Expecter) Create(ctx interface{}, userUUID interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, userUUID)}
}

func (_c *SessionRepository_Create_Call) Run(run func(ctx context.Context, userUUID string)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(_a0 string, _a1 error) *SessionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(context.Context, string) (string, error)) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, sessionUUID
func (_m *SessionRepository) Get(ctx context.Context, sessionUUID string) (model.Session, error) {
	ret := _m.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Session, error)); ok {
		return rf(ctx, sessionUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Session); ok {
		r0 = rf(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID string
func (_e *SessionRepository_Expecter) Get(ctx interface{}, sessionUUID interface{}) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, sessionUUID)}
}

func (_c *SessionRepository_Get_Call) Run(run func(ctx context.Context, sessionUUID string)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(_a0 model.Session, _a1 error) *SessionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Session, error)) *SessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
