// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAMConfig is an autogenerated mock type for the IAMConfig type
type IAMConfig struct {
	mock.Mock
}

type IAMConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *IAMConfig) EXPECT() *IAMConfig_Expecter {
	return &IAMConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *IAMConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IAMConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type IAMConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *IAMConfig_Expecter) Address() *IAMConfig_Address_Call {
	return &IAMConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *IAMConfig_Address_Call) Run(run func()) *IAMConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAMConfig_Address_Call) Return(_a0 string) *IAMConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAMConfig_Address_Call) RunAndReturn(run func() string) *IAMConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAMConfig creates a new instance of IAMConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAMConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAMConfig {
	mock := &IAMConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
