// Code generated for vipshark78 service
// © vipshark78 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoggerConfig is an autogenerated mock type for the LoggerConfig type
type LoggerConfig struct {
	mock.Mock
}

type LoggerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggerConfig) EXPECT() *LoggerConfig_Expecter {
	return &LoggerConfig_Expecter{mock: &_m.Mock}
}

// AsJson provides a mock function with no fields
func (_m *LoggerConfig) AsJson() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsJson")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LoggerConfig_AsJson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsJson'
type LoggerConfig_AsJson_Call struct {
	*mock.Call
}

// AsJson is a helper method to define mock.On call
func (_e *LoggerConfig_Expecter) AsJson() *LoggerConfig_AsJson_Call {
	return &LoggerConfig_AsJson_Call{Call: _e.mock.On("AsJson")}
}

func (_c *LoggerConfig_AsJson_Call) Run(run func()) *LoggerConfig_AsJson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerConfig_AsJson_Call) Return(_a0 bool) *LoggerConfig_AsJson_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerConfig_AsJson_Call) RunAndReturn(run func() bool) *LoggerConfig_AsJson_Call {
	_c.Call.Return(run)
	return _c
}

// EnableOTLP provides a mock function with no fields
func (_m *LoggerConfig) EnableOTLP() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnableOTLP")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LoggerConfig_EnableOTLP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableOTLP'
type LoggerConfig_EnableOTLP_Call struct {
	*mock.Call
}

// EnableOTLP is a helper method to define mock.On call
func (_e *LoggerConfig_Expecter) EnableOTLP() *LoggerConfig_EnableOTLP_Call {
	return &LoggerConfig_EnableOTLP_Call{Call: _e.mock.On("EnableOTLP")}
}

func (_c *LoggerConfig_EnableOTLP_Call) Run(run func()) *LoggerConfig_EnableOTLP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerConfig_EnableOTLP_Call) Return(_a0 bool) *LoggerConfig_EnableOTLP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerConfig_EnableOTLP_Call) RunAndReturn(run func() bool) *LoggerConfig_EnableOTLP_Call {
	_c.Call.Return(run)
	return _c
}

// Level provides a mock function with no fields
func (_m *LoggerConfig) Level() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Level")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoggerConfig_Level_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Level'
type LoggerConfig_Level_Call struct {
	*mock.Call
}

// Level is a helper method to define mock.On call
func (_e *LoggerConfig_Expecter) Level() *LoggerConfig_Level_Call {
	return &LoggerConfig_Level_Call{Call: _e.mock.On("Level")}
}

func (_c *LoggerConfig_Level_Call) Run(run func()) *LoggerConfig_Level_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerConfig_Level_Call) Return(_a0 string) *LoggerConfig_Level_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerConfig_Level_Call) RunAndReturn(run func() string) *LoggerConfig_Level_Call {
	_c.Call.Return(run)
	return _c
}

// OtelCollectorEndpoint provides a mock function with no fields
func (_m *LoggerConfig) OtelCollectorEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OtelCollectorEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoggerConfig_OtelCollectorEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OtelCollectorEndpoint'
type LoggerConfig_OtelCollectorEndpoint_Call struct {
	*mock.Call
}

// OtelCollectorEndpoint is a helper method to define mock.On call
func (_e *LoggerConfig_Expecter) OtelCollectorEndpoint() *LoggerConfig_OtelCollectorEndpoint_Call {
	return &LoggerConfig_OtelCollectorEndpoint_Call{Call: _e.mock.On("OtelCollectorEndpoint")}
}

func (_c *LoggerConfig_OtelCollectorEndpoint_Call) Run(run func()) *LoggerConfig_OtelCollectorEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerConfig_OtelCollectorEndpoint_Call) Return(_a0 string) *LoggerConfig_OtelCollectorEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerConfig_OtelCollectorEndpoint_Call) RunAndReturn(run func() string) *LoggerConfig_OtelCollectorEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceName provides a mock function with no fields
func (_m *LoggerConfig) ServiceName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoggerConfig_ServiceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceName'
type LoggerConfig_ServiceName_Call struct {
	*mock.Call
}

// ServiceName is a helper method to define mock.On call
func (_e *LoggerConfig_Expecter) ServiceName() *LoggerConfig_ServiceName_Call {
	return &LoggerConfig_ServiceName_Call{Call: _e.mock.On("ServiceName")}
}

func (_c *LoggerConfig_ServiceName_Call) Run(run func()) *LoggerConfig_ServiceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoggerConfig_ServiceName_Call) Return(_a0 string) *LoggerConfig_ServiceName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoggerConfig_ServiceName_Call) RunAndReturn(run func() string) *LoggerConfig_ServiceName_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoggerConfig creates a new instance of LoggerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerConfig {
	mock := &LoggerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
