name: CI

on:
  push:
  pull_request:

jobs:
  extract-vars:
    name: Extract Variables from Taskfile
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract.outputs.GO_VERSION }}
      golangci-lint-version: ${{ steps.extract.outputs.GOLANGCI_LINT_VERSION }}
      modules: ${{ steps.extract.outputs.MODULES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Extract variables from Taskfile
        id: extract
        run: |
          chmod +x .github/scripts/extract-versions.sh
          .github/scripts/extract-versions.sh

  lint:
    needs: extract-vars
    uses: ./.github/workflows/lint-reusable.yml
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}
      golangci-lint-version: ${{ needs.extract-vars.outputs.golangci-lint-version }}

  test:
    uses: ./.github/workflows/test-reusable.yml
    needs: [extract-vars, lint]
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}

  coverage:
    if: github.event_name == 'push'
    uses: ./.github/workflows/test-coverage-reusable.yml
    needs: [extract-vars, test]
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}
      gist-id: "6b1f6f0eaf1911e106d22bba2912187d"
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
