services: # Раздел, в котором описываются все контейнеры, необходимые для Payment-сервиса
  # Payment gRPC сервер
  payment-grpc-server:
    build:
      context: ../../..
      dockerfile: deploy/docker/payment/Dockerfile
    container_name: payment-grpc-server
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    healthcheck:
      test: [ "CMD", "/bin/grpc-health-probe", "-addr=localhost:${GRPC_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - microservices-net

networks: # Определение используемой сети
  microservices-net:
    external: true
    # Мы не создаём новую сеть, а подключаемся к внешней, общей для всех микросервисов
    # Её должен создать docker-compose.yml или вручную: docker network create microservices-net

